name: Build

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Was PR merged?
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "PR was merged."
            exit 0
          else
            echo "PR was not merged."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          PACKAGE_URL: ghcr.io/${{ github.repository }}:latest
        run: |
          set -e
          docker build \
            -t ${{ env.PACKAGE_URL }} \
            --build-arg="REPOSITORY_OWNER=${{ github.repository_owner }}" \
            --build-arg="GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --build-arg="REPOSITORY_NAME=${{ github.event.repository.name }}" \
            --build-arg="DOT_ENV=${{ secrets.DOT_ENV }}" \
            --build-arg="EXPOSE_PORT=${{ secrets.EXPOSE_PORT }}" \
            --build-arg="PROJECT_PATH=${{ secrets.PROJECT_PATH }}" .
          docker push ${{ env.PACKAGE_URL }}
