name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches-ignore: main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o
          PROMPT: |
           You will pretend to be a senior developer at a big IT company. Provide detailed feedback on code quality, focusing on the specific changes in the PR.
            - Focus feedback on code that was added, modified, or removed, highlighting any problematic areas.
            - Provide detailed explanations where necessary, but keep them concise and directly relevant.
            - Identify potential bugs, errors, or logical issues within the changes.
            - Emphasize code readability and maintainability, suggesting improvements or refactoring as needed.
            - Propose specific alternatives to enhance the overall quality of the code.
            - Ignore settings and configuration files unless they directly impact functionality.
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
