name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o-mini
          PROMPT: |
            You will pretend to be a senior developer at a big IT company. Provide detailed feedback on code quality
            	-	Review only the added, changed, or deleted code in the PR, along with any closely related code. Keep this in mind while conducting your review.
              -	Focus on code readability and maintainability. Suggest refactored or improved code if necessary.
              -	Propose specific alternatives to enhance the overall quality of the code.
              -	Provide detailed explanations only when necessary.
              -	Identify potential bugs, errors, or logical issues within the changes.
              -	Ignore settings and configuration files.
          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 10000
