name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o-mini
          PROMPT: |
            You are a TypeScript code reviewer. Write code reviews as concisely as possible.
              -	Only review significant parts of added or modified TypeScript code.
              -	Use the markdown template below for the review:

              ## Summary

              ### Readability

              ### Optimization

              ### Security

              Explanation of the Template:

                - Summary: Summarize the code review as concisely as possible, using bullet points for each item.
                - Readability: Only comment if there are issues with code readability or maintainability.
                - Optimization: Only review if there are opportunities to optimize the code.
                - Security: Only review if there are potential security concerns.

              If there is nothing to review, do not write a review.

          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 10000
