name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: docker-compose.yml
          sparse-checkout-cone-mode: false
      - run: |
          set -e
          git checkout HEAD^

      - name: Send docker-compose.yml to ec2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}"

      - name: Deploy server to ec2
        uses: appleboy/ssh-action@v1.0.3
        env:
          PACKAGE_URL: ghcr.io/${{ github.repository }}:latest
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            set -e
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            if [ "$(docker compose ps --filter "status=running" -q)" ]; then
              docker compose down
              docker rmi ${{ env.PACKAGE_URL }}
            fi

            IMAGE_NAME=${{ env.IMAGE_NAME }} docker compose up -d
            rm .docker/config.json
            rm docker-compose.yml
