name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: docker-compose.yml
          sparse-checkout-cone-mode: false
      - run: |
          set -e
          git checkout HEAD^

      - name: Send docker-compose.yml to ec2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}"

      - name: Deploy server to ec2
        uses: appleboy/ssh-action@v1.0.3
        env:
          LATEST_PACKAGE_URL: ghcr.io/${{ github.repository }}:latest
          BASIC_PACKAGE_URL: ghcr.io/${{ github.repository }}
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            set -e

            # .env생성
            printf "%s\n" "${{ secrets.DOT_ENV }}" > .env && echo "IMAGE_NAME=${{ env.LATEST_PACKAGE_URL }}" >> .env

            # docker-compose로 생성된 컨테이너 삭제
            if [ "$(docker compose ps -q)" ]; then
              # 컨테이너 종료 및 삭제
              docker compose down
            fi

            if docker images | grep -q "${{ env.BASIC_PACKAGE_URL }}"; then
              # 기존 이미지 삭제
              docker rmi $(docker images "${{ env.BASIC_PACKAGE_URL }}" -q)
            fi

            # github container registry 로그인
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # 새로 빌드된 이미지 설치
            docker pull ${{ env.LATEST_PACKAGE_URL }}

            # 컨테이너 실행
            docker compose up -d

            # 환경정보 파일 삭제
            rm .docker/config.json
            rm docker-compose.yml
            rm .env
